language: scala
scala:
  - 2.10.4
  - 2.11.0
jdk:
  - oraclejdk7
env:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile

